#!/bin/sh
#

if [ -e numbs ]; then
        echo "File already exists"
else
        echo "File is being created"
        touch numbs
fi

for n in $(seq 1 100);
do
        echo "$n" >> numbs
done
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
~                                                                                                                                                                                                                                            
